### ISSUE TITLE
global leak detected for value and signedBitSet when testing with Mocha

### ISSUE THREAD

**Issue by richardamundson** [stephenwvickers/node-net-snmp#10]
Mocha features a global leak detection mechanism which alerts and fails if your code under test introduces global variables.

What's happening is that somewhere in your code you're missing your var declaration. Mocha is smart enough to detect this in your entire project, not just your test files.

When you don't declare your variables they get attached to the global scope. In Node.js, that's global and in the browser that's window.

I have patched my local clone to fix this, and I'll look into creating a pull request (I'm a GitHub newby though, so it may take some time...)

**Comment by stephenwvickers** [comment]
Thank you, I've merged in your pull request.
