### ISSUE TITLE
Need help with a NoSuchName error

### ISSUE THREAD

**Issue by jurgenhaas** [stephenwvickers/node-net-snmp#13]
When e.g. calling `snmpget 192.168.10.123 1.3.6.1.2.1.2.2.1.16.1` I do get a response like `IF-MIB::ifOutOctets.1 = Counter32: 1200267093`.

However, when using node-net-snmp to retrieve exactly the same OID the response reports an error `RequestFailedError: NoSuchName: 1.3.6.1.2.1.2.2.1.16.1`

Any advise on what I'm doing wrong?

**Comment by stephenwvickers** [comment]
Hi,

Can you provide a packet trace from both queries so that I can compare the requests?

Thanks

Steve

**Comment by jurgenhaas** [comment]
Sorry for the delayed response, I have been out of the office for a couple of days. Just retried today and I'm getting `Unknown engine ID` errors when using snmpget like above and I couldn't figure out yet, why that is the case. However, searching through Google I realized that my remote host is configured such that SNMP v3 is used with authentication and maybe this is not supported by node-net-snmp yet?

**Comment by stephenwvickers** [comment]
SNMP v3 is currently not supported.
