### ISSUE TITLE
BitString support

### ISSUE THREAD

**Issue by mannyveloso** [stephenwvickers/node-net-snmp#16]
hi!

Are you thinking of adding BitString support anytime soon?

Thanks!

**Comment by stephenwvickers** [comment]
Hi,

From what I understand BitString is deprecated.

Steve

**Comment by mannyveloso** [comment]
I’m not surprised…but they’re still out there.

I had the same problem in the other snmp library, I’ll see if I can get support for it together. I don’t actually need it, since I’m now getting specific counters…but it causes the treewalk to fail for some of my older devices.

---
Manny Veloso / technical person
o: +360 859 1780


Follow SmartRG<http://www.smartrg.com/> news and events on Facebook<https://www.facebook.com/SmartRG?fref=ts> | Twitter<https://twitter.com/SRGcrew> | LinkedIn<https://www.linkedin.com/company/2568791?trk=vsrp_companies_res_name&trkInfo=VSRPsearchId%3A80173221376409258784%2CVSRPtargetId%3A2568791%2CVSRPcmpt%3Aprimary> | YouTube<https://www.youtube.com/channel/UCxs7PruCYyHnuAVHO_oQAmQ>

From: Stephen Vickers
Reply-To: stephenwvickers/node-net-snmp
Date: Wednesday, June 8, 2016 at 4:02 AM
To: stephenwvickers/node-net-snmp
Cc: manny veloso, Author
Subject: Re: [stephenwvickers/node-net-snmp] BitString support (#16)


Hi,

From what I understand BitString is deprecated.

Steve

**Comment by stephenwvickers** [comment]
It doesn't look difficult to support, would you like me to go ahead and implement it?

I'm not sure when I can do this, I am currently laying a patio in the back garden and don't have a lot of time right now :)

**Comment by mannyveloso** [comment]
I’m not sure - I was using it as part of an SNMP walk, but now that I have the oids I need I don’t need it. I suppose it would be good for completeness. P3?

**Comment by stephenwvickers** [comment]
If you don't need it them I am inclined not to implement it.

If you strongly suggest I implement it then I will look to do so though :)
