### ISSUE TITLE
PDU types mis-defined

### ISSUE THREAD

**Issue by shanept** [stephenwvickers/node-net-snmp#19]
The following is an excerpt from the [current code-base for the PDU types][0].

    var PduType = {
    	160: "GetRequest",
    	161: "GetNextRequest",
    	162: "GetResponse",
    	163: "SetRequest",
    	164: "Trap",
    	165: "GetBulkRequest",
    	166: "InformRequest",
    	167: "TrapV2",
    	168: "Report"
    };

According to the RFCs for [SNMPv2][1], and the [amendment released with SNMPv3][2], these values have been mis-defined.

[0]: https://github.com/stephenwvickers/node-net-snmp/blob/cc4860b1b244b9822979d9822056a30e1be6cbb4/index.js#L69 "var PduType"
[1]: https://tools.ietf.org/html/rfc1905#section-3 "Protocol operations for SNMP version 2"
[2]: https://tools.ietf.org/html/rfc3416#section-3 "Version 2 of Protocol Operations for SNMPv2"

Stephen, I can not currently create a pull request for this due to my current works with this project (ref. emails). The following is my suggestion:

    var PduType = {
    	0: "GetRequest",
    	1: "GetNextRequest",
    	2: "GetResponse",
    	3: "SetRequest",
    	4: "Trap",				// Obsoleted in SNMPv2 (by RFC 1448)
    	5: "GetBulkRequest",
    	6: "InformRequest",
    	7: "TrapV2",
    	8: "Report"
    };

Simply reduce the index values of each by 160.

**Comment by stephenwvickers** [comment]
Hi Shane,

Are you sure this is the case?

Try a packet capture :)

Steve

**Comment by shanept** [comment]
Hi Stephen,

I have looked into it a bit more, it's more complex than I thought.

So my understanding, currently, is that these values should be 0-8 in the SNMP software, and that there is a bit-level operation on it during encoding to ASN1.

I can't find anything in the RFCs for this - I will continue to investigate and see if I'm on the right track.

Thanks again,
Shane

**Comment by stephenwvickers** [comment]
That's okay, I also remember trying to work out the mystery, then I read parts of the ASN1 spec and it all made sense :)

It would be nice if there was a mention of it in the RFC, but I guess if you are implementing something like SNMP you should really read all the relevant standards :S
