### ISSUE TITLE
Request ID size

### ISSUE THREAD

**Issue by rwilcox73** [stephenwvickers/node-net-snmp#21]
I've noticed that the code is using a rather large number for the request id, and my device must be using a signed value to store the request id and the return request id is coming back negative.  Could a lower number be used for the request-id or could we seed a number to ensure that the value isn't too large?

**Comment by stephenwvickers** [comment]
The request ID is a signed integer and can be positive or negative.

It probably makes sense to be able to seed the request ID's and count up.

For the life of me I cannot remember why we use random numbers :)

I will take a closer look.

**Comment by stephenwvickers** [comment]
Hi, the main reason for generating random ID's is mainly to prevent guessing the next ID, and using this to spoof a response.  I am not inclined to change this behaviour, however I would be open to setting a maximum ID, i.e. something would always result in a signed integer if stored as an unsigned.

Would this help?

**Comment by rwilcox73** [comment]
yeah, as long as it's always unsigned that should be fine.
