### ISSUE TITLE
Using traps

### ISSUE THREAD

**Issue by jjelizegi** [stephenwvickers/node-net-snmp#23]
Hi,

I am starting to use this node-net-snmp package to deal with a Remote I/O module that sends traps in case state of the inputs changes.  I have been able so far to get the values of the digital inputs via get function and now I am tryng to collect the value of a particular DO and to respond to a TRAP . What must I do to listen to a particular trap emited by this device?

**Comment by stephenwvickers** [comment]
The module doesn't currently support listening for SNMP traps.

**Comment by markabrahams** [comment]
@jjelizegi - FYI a trap/inform receiver is now implemented for this library, and is available in the latest NPM (added in v2.1.0).  Documentation on using the Receiver is in the README.md:
https://github.com/markabrahams/node-net-snmp
