### ISSUE TITLE
request fails due to community string  

### ISSUE THREAD

**Issue by ilanbe** [stephenwvickers/node-net-snmp#24]
I using node-net-snmp for access SNMP v1, and receiving the following message 
'Community \'public\' in request does not match community \'\' in response' } varbinds = undefined   
since "snmpget -v1 -c public"  work successfully on the same OID, I'm wondering is this check is required. or is there a way to override it. 

Thanks 
Ilan

**Comment by stephenwvickers** [comment]
Can you look at the network traffic (using Wireshark/tcpdump) and see if the community in the response is in fact empty?

**Comment by stephenwvickers** [comment]
No more information from user, so closing the ticket.  Please re-open if it's still an issue and review the network traffic with a sniffer as per previous comment.
