### ISSUE TITLE
The _generateId() function randomly returns negative ID's resulting in response parsing issues and timeouts

### ISSUE THREAD

**Issue by h32axc** [stephenwvickers/node-net-snmp#31]
Hi, I just started trying to use node-net-snmp (and node-red-node-snmp, which uses node-net-snmp) and was surprised to encounter very basic problems, even with the sample .js on the node-net-snmp homepage.  For example:

- .get of 1 or 2 OID's would sometimes work, but often would timeout
- .subtree would never work - always fails with timeout

When I reverted to index.js v. ecc688b, everything works fine - all .get's work reliably, and .subtree works fine.

I'm using node-net-snmp in Node.JS 8.9.3 in Windows 10 x64.  I'm not sure if the changes to index.js are the problem or if there is some configuration issue, but for now I'm happy with the older version of index.js.

**Comment by Scarysize** [comment]
Yes, I have the same issue with the `.walk` method. If I downgrade to version `1.1.19` everything works fine, not request timeouts.

**Comment by hluedeke** [comment]
I can confirm that this is happening with `.get()` on both 1.2.1 and 1.2.0

**Comment by stephenwvickers** [comment]
Hi All,

It appears that I didn't properly verify a merge request which caused in issue in the function generating request ID's.

I have addressed this, and it will be resolved in 1.2.2 which I am about to release to npm.

Apologies for the inconvenience.

Steve
