### ISSUE TITLE
Cannot access to "private" oids

### ISSUE THREAD

**Issue by leviArista** [stephenwvickers/node-net-snmp#35]
I am new at using SNMP protocol, so excuse me if i misspell technical details.

I am working with this this library to get some information from a "Rajant" antena [(model)](https://www.tessco.com/products/displayProductInfo.do?sku=510538)

When i attempt to get info from oids that i suppose are general, like `sysDescr: [1.3.6.1.2.1.1.1.0]` or `sysObjectID: [1.3.6.1.2.1.1.2.0]` i get the correct values from them

Nevertheless when i try to use some "private" Rajant oids like `freeMemory: [1.3.6.1.4.1.34861.1.3]` or `uptime: [1.3.6.1.4.1.34861.1.5]` I cannot access values from them. The only one i can get is `serialNumber: [1.3.6.1.4.1.34861.1.1] = ME4-2450R-35483`.

These oids are obtained from this [rajant mib file](https://github.com/stephenwvickers/node-net-snmp/files/1880573/rajant-mib.txt)

And my code is as follows:

```javascript
var options = {
              port: 9002,
              retries: 1,
              timeout: 100000,
              version: snmp.Version1,
              idBitsSize: 16
            };

var session = snmp.createSession ("192.168.0.56", "public",options);

oids = ["1.3.6.1.4.1.34861.1.3]","1.3.6.1.4.1.34861.1.5]"];

session.get (oids, function (error, varbinds) {
  if (error) {
    console.error (error);
  } else {
    for (var i = 0; i < varbinds.length; i++)
      if (snmp.isVarbindError (varbinds[i])){
        console.error (snmp.varbindError (varbinds[i]));
      }
      else{
        console.log (varbinds[i].oid + " = " + varbinds[i].value);
      }

  }
});

session.trap (snmp.TrapType.LinkDown, function (error) {
  if (error)
    console.error (error);
});
```

I get an error from these oids, i can't get their values

I am asking for support to understand what is happening, 

***Am I using the library incorrectly?***
***Do i have to make some kind of auth to get this information?***
***Does exist this difference between "private" and "general" oids or is it just my perception?***
***How can i get those values from private oids?***

I would muchly appreciate if i get some explanation. Thanks in advance

**Comment by stephenwvickers** [comment]
Hi @leviArista 

If the OID's are scalar values you will need to appned `.0`, i.e. `1.3.6.1.4.1.34861.1.3.0`.

Try that for the scalar OID's and let me know.

Steve

**Comment by leviArista** [comment]
@stephenwvickers Sorry for my late replying.

I tried to get the value by appending `.0`, yet I couldn't do that. I think that's because it is private information to access.

Rajant has an [API product](https://www.rajant.com/products/network-management-tools/bcapi/), that they sell to manage networks with devices of their property. So I think that they don't let access those values through `SNMP` because they can only be accessed through their API that I am supossed to buy.

Anyway thanks for all, your library is so useful, you are making a good work! 😉
