### ISSUE TITLE
snmp.createSession() should be where the callback is defined

### ISSUE THREAD

**Issue by andrewhodel** [stephenwvickers/node-net-snmp#36]
Right now if I have an snmp session created for a host and run two unique oid walk requests, each walk request get's it's own feed callback and done callback.

The walk requests all call the done callback of the latest (in sequence of when the instances were created) walk request.  That's fine but that means that the done callback or the data callback of things like a single oid request should be defined in snmp.createSession().

The same is true of the feed callback.

**Comment by andrewhodel** [comment]
Actually, both callbacks get called for both the feed and done callbacks.

**Comment by stephenwvickers** [comment]
The documentation is correct, you must pass a/some callback(s) to each method resulting in SNMP requests.  If you are not seeing this please provide a working program which emits the issue you describe.

**Comment by andrewhodel** [comment]
It doesn't even walk correctly now.  Walk just goes wild and doesn't even limit itself to sub items of the requested oid.

And with this code, the done callback never even gets called.  This is node v10.0.0

Code follows the error.

```
root@debian:~/test# snmpwalk -v2c -c public 10.99.0.1 1.3.6.1.2.1.1
iso.3.6.1.2.1.1.1.0 = STRING: "RouterOS RB951-2n"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.14988.1
iso.3.6.1.2.1.1.3.0 = Timeticks: (253506600) 29 days, 8:11:06.00
iso.3.6.1.2.1.1.4.0 = STRING: "asdf"
iso.3.6.1.2.1.1.5.0 = STRING: "asdf"
iso.3.6.1.2.1.1.6.0 = STRING: "asdf"
iso.3.6.1.2.1.1.7.0 = INTEGER: 78
root@debian:~/test# vim snmpproblem.js
root@debian:~/test# node snmpproblem.js
^C
root@debian:~/test# ^C
root@debian:~/test# vim snmpproblem.js
root@debian:~/test# node snmpproblem.js
1.3.6.1.2.1.1.1.0|RouterOS RB951-2n
1.3.6.1.2.1.1.1.0|RouterOS RB951-2n
1.3.6.1.2.1.1.2.0|1.3.6.1.4.1.14988.1
1.3.6.1.2.1.1.2.0|1.3.6.1.4.1.14988.1
1.3.6.1.2.1.1.3.0|253517700
1.3.6.1.2.1.1.3.0|253517700
1.3.6.1.2.1.1.4.0|asdf
1.3.6.1.2.1.1.4.0|asdf
1.3.6.1.2.1.1.5.0|asdf
1.3.6.1.2.1.1.5.0|asdf
1.3.6.1.2.1.1.6.0|asdf
1.3.6.1.2.1.1.6.0|asdf
1.3.6.1.2.1.1.7.0|78
1.3.6.1.2.1.1.7.0|78
1.3.6.1.2.1.2.1.0|9
1.3.6.1.2.1.2.1.0|9
1.3.6.1.2.1.2.2.1.1.1|1
1.3.6.1.2.1.2.2.1.1.1|1
1.3.6.1.2.1.2.2.1.1.2|2
1.3.6.1.2.1.2.2.1.1.2|2
1.3.6.1.2.1.2.2.1.1.3|3
1.3.6.1.2.1.2.2.1.1.3|3
1.3.6.1.2.1.2.2.1.1.4|4
1.3.6.1.2.1.2.2.1.1.4|4
1.3.6.1.2.1.2.2.1.1.5|5
1.3.6.1.2.1.2.2.1.1.5|5
1.3.6.1.2.1.2.2.1.1.6|6
1.3.6.1.2.1.2.2.1.1.6|6
1.3.6.1.2.1.2.2.1.1.7|7
1.3.6.1.2.1.2.2.1.1.7|7
1.3.6.1.2.1.2.2.1.1.8|8
1.3.6.1.2.1.2.2.1.1.8|8
1.3.6.1.2.1.2.2.1.1.9|9
1.3.6.1.2.1.2.2.1.1.9|9
1.3.6.1.2.1.2.2.1.2.1|ether1
1.3.6.1.2.1.2.2.1.2.1|ether1
1.3.6.1.2.1.2.2.1.2.2|ether2
1.3.6.1.2.1.2.2.1.2.2|ether2
1.3.6.1.2.1.2.2.1.2.3|ether3
1.3.6.1.2.1.2.2.1.2.3|ether3
1.3.6.1.2.1.2.2.1.2.4|ether4
1.3.6.1.2.1.2.2.1.2.4|ether4
1.3.6.1.2.1.2.2.1.2.5|ether5
1.3.6.1.2.1.2.2.1.2.5|ether5
1.3.6.1.2.1.2.2.1.2.6|wlan1
1.3.6.1.2.1.2.2.1.2.6|wlan1
1.3.6.1.2.1.2.2.1.2.7|bridge1
1.3.6.1.2.1.2.2.1.2.7|bridge1
1.3.6.1.2.1.2.2.1.2.8|bridge2
1.3.6.1.2.1.2.2.1.2.8|bridge2
1.3.6.1.2.1.2.2.1.2.9|wlan2
1.3.6.1.2.1.2.2.1.2.9|wlan2
1.3.6.1.2.1.2.2.1.3.1|6
1.3.6.1.2.1.2.2.1.3.1|6
1.3.6.1.2.1.2.2.1.3.2|6
1.3.6.1.2.1.2.2.1.3.2|6
1.3.6.1.2.1.2.2.1.3.3|6
1.3.6.1.2.1.2.2.1.3.3|6
1.3.6.1.2.1.2.2.1.3.4|6
1.3.6.1.2.1.2.2.1.3.4|6
1.3.6.1.2.1.2.2.1.3.5|6
1.3.6.1.2.1.2.2.1.3.5|6
1.3.6.1.2.1.2.2.1.3.6|71
1.3.6.1.2.1.2.2.1.3.6|71
1.3.6.1.2.1.2.2.1.3.7|209
1.3.6.1.2.1.2.2.1.3.7|209
1.3.6.1.2.1.2.2.1.3.8|209
1.3.6.1.2.1.2.2.1.3.8|209
1.3.6.1.2.1.2.2.1.3.9|71
1.3.6.1.2.1.2.2.1.3.9|71
1.3.6.1.2.1.2.2.1.4.1|1500
1.3.6.1.2.1.2.2.1.4.1|1500
1.3.6.1.2.1.2.2.1.4.2|1500
1.3.6.1.2.1.2.2.1.4.2|1500
1.3.6.1.2.1.2.2.1.4.3|1500
1.3.6.1.2.1.2.2.1.4.3|1500
1.3.6.1.2.1.2.2.1.4.4|1500
1.3.6.1.2.1.2.2.1.4.4|1500
1.3.6.1.2.1.2.2.1.4.5|1500
1.3.6.1.2.1.2.2.1.4.5|1500
1.3.6.1.2.1.2.2.1.4.6|1500
1.3.6.1.2.1.2.2.1.4.6|1500
1.3.6.1.2.1.2.2.1.4.7|1500
1.3.6.1.2.1.2.2.1.4.7|1500
1.3.6.1.2.1.2.2.1.4.8|1500
1.3.6.1.2.1.2.2.1.4.8|1500
1.3.6.1.2.1.2.2.1.4.9|1500
1.3.6.1.2.1.2.2.1.4.9|1500
1.3.6.1.2.1.2.2.1.5.1|0
1.3.6.1.2.1.2.2.1.5.1|0
1.3.6.1.2.1.2.2.1.5.2|100000000
1.3.6.1.2.1.2.2.1.5.2|100000000
1.3.6.1.2.1.2.2.1.5.3|100000000
1.3.6.1.2.1.2.2.1.5.3|100000000
1.3.6.1.2.1.2.2.1.5.4|100000000
1.3.6.1.2.1.2.2.1.5.4|100000000
1.3.6.1.2.1.2.2.1.5.5|0
1.3.6.1.2.1.2.2.1.5.5|0
1.3.6.1.2.1.2.2.1.5.6|50000000
1.3.6.1.2.1.2.2.1.5.6|50000000
1.3.6.1.2.1.2.2.1.5.7|100000000
1.3.6.1.2.1.2.2.1.5.7|100000000
1.3.6.1.2.1.2.2.1.5.8|100000000
1.3.6.1.2.1.2.2.1.5.8|100000000
1.3.6.1.2.1.2.2.1.5.9|50000000
1.3.6.1.2.1.2.2.1.5.9|50000000
1.3.6.1.2.1.2.2.1.6.1|��m
1.3.6.1.2.1.2.2.1.6.1|��m
1.3.6.1.2.1.2.2.1.6.2|��m
1.3.6.1.2.1.2.2.1.6.2|��m
1.3.6.1.2.1.2.2.1.6.3|��m
1.3.6.1.2.1.2.2.1.6.3|��m
1.3.6.1.2.1.2.2.1.6.4|��m
1.3.6.1.2.1.2.2.1.6.4|��m
1.3.6.1.2.1.2.2.1.6.5|��m
1.3.6.1.2.1.2.2.1.6.5|��m
1.3.6.1.2.1.2.2.1.6.6|��m
1.3.6.1.2.1.2.2.1.6.6|��m
1.3.6.1.2.1.2.2.1.6.7|��m
1.3.6.1.2.1.2.2.1.6.7|��m
1.3.6.1.2.1.2.2.1.6.8|��m
1.3.6.1.2.1.2.2.1.6.8|��m
1.3.6.1.2.1.2.2.1.6.9|��m
1.3.6.1.2.1.2.2.1.6.9|��m
1.3.6.1.2.1.2.2.1.7.1|1
1.3.6.1.2.1.2.2.1.7.1|1
1.3.6.1.2.1.2.2.1.7.2|1
1.3.6.1.2.1.2.2.1.7.2|1
1.3.6.1.2.1.2.2.1.7.3|1
1.3.6.1.2.1.2.2.1.7.3|1
1.3.6.1.2.1.2.2.1.7.4|1
1.3.6.1.2.1.2.2.1.7.4|1
^C
```

```
root@debian:~/test# cat snmpproblem.js
var snmp = require('net-snmp');

var oid = "1.3.6.1.2.1.1";

function doneCbtwo (error) {
    if (error)
        console.error (error.toString ());

        console.log('doneCb');
}

function feedCbtwo (varbinds) {
    for (var i = 0; i < varbinds.length; i++) {
        if (snmp.isVarbindError (varbinds[i])) {
            console.error (snmp.varbindError (varbinds[i]));
        } else {
            console.log (varbinds[i].oid + "|" + varbinds[i].value);
        }
    }

        //console.log('feedCbtwo');
}

function doneCb (error) {
    if (error)
        console.error (error.toString ());

        console.log('doneCbtwo');

}

function feedCb (varbinds) {
    for (var i = 0; i < varbinds.length; i++) {
        if (snmp.isVarbindError (varbinds[i])) {
            console.error (snmp.varbindError (varbinds[i]));
        } else {
            console.log (varbinds[i].oid + "|" + varbinds[i].value);
        }
    }
        //console.log('feedCb');
}

var maxRepetitions = 1;

var session = snmp.createSession('10.99.0.1', 'public', {version: snmp.Version2c});

function loop() {
        session.walk (oid, maxRepetitions, feedCb, doneCb);
        session.walk (oid, maxRepetitions, feedCbtwo, doneCbtwo);
}

setInterval(loop, 30000);
```

**Comment by stephenwvickers** [comment]
> It doesn't even walk correctly now.  Walk just goes wild and doesn't even limit itself to sub items of the requested oid.

The `walk()` method does NOT go wild, you just haven't read and understood the documentation: "The walk() method fetches the value for all OIDs lexicographically following a specified OID in the MIB tree.".  The behavior you have reported appears to be correct.

I think you are looking for the `subtree()` method: "The subtree() method fetches the value for all OIDs lexicographically following a specified OID in the MIB tree which have the specified OID as there base. For example, the OIDs sysName (1.3.6.1.2.1.1.5.0) and sysLocation (1.3.6.1.2.1.1.6.0) both have the same base system (1.3.6.1.2.1.1) OID."

Also note, this module does not claim to be, and is not, a drop in replacement for the net-snmp utilities.  That is, they are NOT the benchmark for this module.

> And with this code, the done callback never even gets called.  This is node v10.0.0

Of course not, I can see from the output you issued a CTRL+C, so you never gave it a chance to finish walking the MIB tree.  Also note, if you see a long pause when fetching SNMP OIDs, it can sometimes be the device being walked and not the program.  The device maybe walking and calculating the next valid value in the MIB tree, and may appear to hang.  A network trace will show if the device has not responded to a request yet.

People are more willing to help if they are not met with hostility.

**Comment by andrewhodel** [comment]
I'm sorry that you think asking you to document your required event handlers is unfriendly.

I'm certainly not "of or belonging to a military enemy".

And I hit ctrl-c after waiting quite some time.

**Comment by stephenwvickers** [comment]
> I'm sorry that you think asking you to document your required event handlers is unfriendly.

The event handler is NOT required.

> And I hit ctrl-c after waiting quite some time.

Like I said, this could be down to the device you are polling, and you should consider using a packet trace to understand what is going on.

**Comment by andrewhodel** [comment]
Well, to quote you, it is required to handle the event.

That is what you said 15 days ago.

```
I don't think you understand exactly what is going on. The module already uses event emitter:

https://github.com/stephenwvickers/node-net-snmp/blob/master/index.js#L936

Your problem is that you don't catch the error event.

This is the same for every module, if you don't catch the error event, and one is generated by any module, it will bring down your process.
```

https://github.com/stephenwvickers/node-net-snmp/issues/34

**Comment by stephenwvickers** [comment]
Yes, your program crashes because you don't catch the error event, but you confuse this with "required" though.  I never said it was "required", you are miss-quoting me.

When using any module, including Node.js built-in modules, *you* will have to decide what strategy you will use for handling errors, and *you* should decide if you want to catch errors or not.

This is exactly the same with various built-in Node.js modules, if you don't handle error events they will bring down your program!

**Comment by andrewhodel** [comment]
That's just not true, you can return an error in a callback without using an event.

All you have to do, regarding your complaint about snmp and udp not basically binding the initial message and the response is use a queue and a message id and not call the callback until either the timeout is reached or the response is received.

In that fashion you would not have to force an error event.  On the other hand, it is completely fine to force an error event to be handled, however you should document it and you chose not to.

That's what ticked you off in the first place.

**Comment by stephenwvickers** [comment]
I'm sorry, your rhetoric will not work. I am not "ticked" off.  I don't care for hostility, only correctness.

I just don't think you understand. If you can't parse a response message because say it's not valid, you have no idea which request it is for, therefore you can't call it's callback.

Like I said before, it is not required to catch the error event.

*You* will have to determine what *you* should do when errors occur.

**Comment by andrewhodel** [comment]
```
I just don't think you understand. If you can't parse a response message because say it's not valid, you have no idea which request it is for, therefore you can't call it's callback.
```

Dude you must just be going for the sake of it.  What you are explaining is getting a letter in the mail that was a blank sheet of paper.  You send the "error message" for the particular request when the "timeout" is reached.  Basically, you didn't get a response after a period of time and at that point you call it a timeout and you then call the callback.

That's the whole point of callbacks!

It's not rhetoric, it's a basic understanding!

**Comment by stephenwvickers** [comment]
I don't know why you keep trying to use rhetoric on me, I wish you would stop it.

I disagree with you wanting to ignore malformed messages, there is a large different between no message and an invalid one.

You are the only one, since releasing the library several years ago, who is complaining about the semantics.

**Comment by stephenwvickers** [comment]
If you don't care about malformed messages, just catch the error and their them away as part of your error handling strategy.

**Comment by andrewhodel** [comment]
```
If you don't care about malformed messages, just catch the error and throw them away as part of your error handling strategy.
```

This is exactly what I said it step one, I just said why don't you use a callback instead of an error handler so that it's not required or at least document that it's needed?

Why is so hard to:

```
git clone https://github.com/stephenwvickers/node-net-snmp
cd node-net-snmp
echo "\nIt is required that you use an error handler, this is a warning.  If a malformed packet is received the program will throw an error that is required by this library to be caught.\n\n" >> README.md
git commit -m 'added note about required error handler to README.md'
git push origin master
sed s/n\.n\.n\./7.7.7/g package.json
npm publish
````


That is all you do, really.

**Comment by stephenwvickers** [comment]
> It seems at this point you are not talking about udp or snmp.

Nope, still SNMP.

> What would you say in the event of a broadcast stream, seeing as anyone can create a 192 network and broadcast. If packets were lost in a video stream, are you expecting them to handle all of them? Do you want them logged and combed through later? Are you going to delta the logs of each broadcast client? It's just absurd what you are proposing here.

This doesn't seem relevant to SNMP.

> I just can't understand how you got past actually talking about what you are thinking about, seeing as the goal is that the technology works and functions correctly.

I am not sure what you mean here.

> Who is going to parse broken messages. At best someone would just increment a bullshit counter for the particular IP.

Mm, that's a bit naive, you don't get to dictate the error handling strategy for other users.  At least with the current API you get the opportunity to see those errors.

>     If you don't care about malformed messages, just catch the error and throw them away as part of your error handling strategy.
> 
> This is exactly what I said it step one, I just said why don't you use a callback instead of an error handler so that it's not required or at least document that it's needed?

I really don't see the difference between the two.  If you want to handle the errors then handle the event, i.e. like try/catch with exceptions if you don't catch them they will bring down your program.

> Why is it so hard to:
> 
>     git clone https://github.com/stephenwvickers/node-net-snmp
>     cd node-net-snmp
>     echo "\nIt is required that you use an error handler, this is a warning.  If a malformed packet is received the program will throw an error that is required by this library to be caught.\n\n" >> README.md
>     git commit -m 'added note about required error handler to README.md'
>     git push origin master
>     sed s/n\.n\.n\./7.7.7/g package.json
>     npm publish
> 
> Yea I know, go make something else the same version then change the sed line to include your package name, this is all basic.
> 
> That is all you do, really.

As I said previously, catching the error is NOT required.  If you want to handle errors, then handle the event.
