### ISSUE TITLE
Returning both and error and varbinds in the same .get() call

### ISSUE THREAD

**Issue by hluedeke** [stephenwvickers/node-net-snmp#39]
I am working on a project that remotely communicates with SNMP equipment using the session.get() function from this library. We're finding it very difficult to debug when a single point throws off the whole SNMP read, especially since equipment of the same model sometimes has that OID defined and sometimes doesn't.

We have error logs, but it's not very intuitive or user friendly for us to just fail the whole read if one point fails (aka on a NoSuchName exception), especially since our remote reads are on timers. It'd be great if we could still get a returned list of varbinds with values for those SNMP OIDs that did not cause an error, even when an error is present.

Is there a reason why the session.get() returns either an error or a list of varbinds, but not both? I've taken a look at the library and have a grasp on it (though I'm certainly not an expert), and I'd be willing to help work on this if it's viable.

Thanks!

**Comment by stephenwvickers** [comment]
Hi @hluedeke 

My interpretation of the RFC's are that if an OID cannot be found then the receiving entity will send a response PDU which will indicate error which will not include any varbinds.  I believe this is the section which details this:

https://github.com/stephenwvickers/node-net-snmp/blob/master/ref/rfc/v1/rfc1067.txt#L1052

I tried to follow the RFC's closely, so this is why it treats it as error.

SNMP v2 works differently, and you should get values for the other items, as per here:

https://github.com/stephenwvickers/node-net-snmp/blob/master/ref/rfc/v2c/rfc3416.txt#L548

A missing PDU would not set the error index field, and cause the request to fail, at least that is my interpretation of the RFC's.

Regards

Steve

**Comment by hluedeke** [comment]
First of all, thanks for the quick response. You are awesome.

Second of all, we are indeed using SNMP v2c for these remote polls. I will try and see if I can get the list of varbinds back despite the error (which was being caught as an error in the callback, not in the varbind object).

I'll let you know what I find. Thanks!

**Comment by stephenwvickers** [comment]
That's no problem at all.

Checkout the error status and error index of the response pdu, they should in theory be 0.

Steve

**Comment by hluedeke** [comment]
I found my error - I was not setting the version explicitly in the options object of .createSession(), and it was defaulting to v1 (facepalm). I can confirm that v2c works as mentioned above.

Thanks for the help!

**Comment by neumartin** [comment]
Hi!
Nice work, awesome library!
I have the same error but can't find the solution.
My configuration is this:

```
let options = {
    port: 161,
    retries: 1,
    timeout: 5000,
    backoff: 1.0,
    transport: "udp4",
    trapPort: 162,
    version: snmp.Version2c,
    backwardsGetNexts: true,
    idBitsSize: 32
};
```
I send 3 OIDs

```
                let session = snmp.createSession(netDevice.ip, "public", options);
                let oids = [oidGenericModel, oidGenericContadorByN, oidGenericSerial];

                session.get(oids, function (error, varbinds) { ...
```

But I recive an error "NoSuchName: 1.3.6.1.2.1.43.10.2.1.4.1.1" and varbinds is undefined.
If I remove 1.3.6.1.2.1.43.10.2.1.4.1.1, works fine.

Any help will be appreciated @hluedeke @gavinaiken @stephenwvickers 
Thanks!

**Comment by stephenwvickers** [comment]
@neumartin That looks like a scalar value so maybe try appeneding `.0`, i.e.:

```
1.3.6.1.2.1.43.10.2.1.4.1.1.0
```

**Comment by neumartin** [comment]
@stephenwvickers thaks for the answer!
This OID works, this not: "1.3.6.1.2.1.43.5.1.1.17.1"

If I run this:

```
const oidGenericModel = "1.3.6.1.2.1.43.5.1.1.16.1";
const oidGenericContadorByN = "1.3.6.1.2.1.43.10.2.1.4.1.1";
const oidGenericSerial = "1.3.6.1.2.1.43.5.1.1.17.1";

let session = snmp.createSession(netDevice.ip, "public", options);
let oids = [oidGenericModel, oidGenericContadorByN, oidGenericSerial];

session.get(oids, function (error, varbinds) {...
```

I get:
```
message:"NoSuchName: 1.3.6.1.2.1.43.10.2.1.4.1.1"
name:"RequestFailedError"
stack:"RequestFailedError: NoSuchName: 1.3.6.1.2.1.43.10.2.1.4.1.1
    at Req.Session.onSimpleGetResponse [as onResponse] (/home/martin/Trabajo/inkside/src/clients/inkside-electron/node_modules/net-snmp/index.js:2062:16)
    at Session.onMsg (/home/martin/Trabajo/inkside/src/clients/inkside-electron/node_modules/net-snmp/index.js:2036:9)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage [as onmessage] (dgram.js:861:8)"
status:2
```

But if I remove "1.3.6.1.2.1.43.5.1.1.17.1"; works fine.
Why if some OID have a problem I can't get the others?

Thanks!

**Comment by stephenwvickers** [comment]
I believe you are using SNMP v1 so if one fails the entire request fails.

If you use SNMP v2c then the failure of a single OID won't fail the entire request.

**Comment by unchained-za** [comment]
Hi, I am actually working on the module at the moment, but I'll have to find the issue again to see what exactly happened. It's been a while. 
Tanks! 

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived.

**Comment by neumartin** [comment]
> I believe you are using SNMP v1 so if one fails the entire request fails.
> 
> If you use SNMP v2c then the failure of a single OID won't fail the entire request.

Strange, I use this options:

```
let options = {
    port: 161,
    retries: 0,
    timeout: 5000,
    backoff: 1.0,
    transport: "udp4",
    trapPort: 162,
    version: snmp.Version2c,
    backwardsGetNexts: true,
    idBitsSize: 32
};
```

**Comment by stephenwvickers** [comment]
@neumartin Can you post an example program which emits the issue.  Otherwise I'm just guessing what the code does :)

**Comment by neumartin** [comment]
Sure!

```
let snmp = require("net-snmp");

//Generic
const oidGenericModel = "1.3.6.1.2.1.43.5.1.1.16.1";
const oidGenericContadorByN = "1.3.6.1.2.1.43.10.2.1.4.1.1";
const oidGenericSerial = "1.3.6.1.2.1.43.5.1.1.17.1";
const ipPrinter = "192.168.11.112";

let options = {
    port: 161,
    retries: 0,
    timeout: 5000,
    backoff: 1.0,
    transport: "udp4",
    trapPort: 162,
    version: snmp.Version2c,
    backwardsGetNexts: true,
    idBitsSize: 32
};

let session = snmp.createSession(ipPrinter, "public", options);
let oids = [oidGenericModel, oidGenericContadorByN]; //Works!!
let oidsWithSerial = [oidGenericModel, oidGenericContadorByN, oidGenericSerial]; //Not working

session.get(oids, function (error, varbinds) {
    if (error) {
        console.error(error);
    } else {
        for (var i = 0; i < varbinds.length; i++) {
            if (!snmp.isVarbindError(varbinds[i])) {
                console.log(ipPrinter + ": " + varbinds[i].oid + " = " + varbinds[i].value);
            } else
                console.error(ipPrinter + ": " + snmp.varbindError(varbinds[i]));
        }
    }
    session.close();
});
```

If you use the array oids works fine, but if you use oidsWithSerial not.
You can change ipPrinter for the ip of any printer in your network.

Thanks!!!

**Comment by stephenwvickers** [comment]
@neumartin Looking at the OIDs, the first one should probably be "1.3.6.1.2.1.43.5.1.1.16.0" since the scalar OID looks to me to actially be "1.3.6.1.2.1.43.5.1.1.16" and normally ".0" is used for the instance of the OID.

The second OID looks like it's part of a table, so likely works by accident for you - unless you actually wanted to get that part of the table.

The third is like the first, and possibly in this case the device does not accept ".1" as an instance for that OID.  You should try using "1.3.6.1.2.1.43.5.1.1.17.0" for the third.

**Comment by neumartin** [comment]
@stephenwvickers awesome response time!, thanks!
The first two works fine, and as you said, I need the scalar value.

See the result with only the first two:

```
1.3.6.1.2.1.43.5.1.1.16.1 = RICOH Aficio SP 3510DN (397b70)
1.3.6.1.2.1.43.10.2.1.4.1.1 = 147372
```

But if I use the third, even if I use "1.3.6.1.2.1.43.5.1.1.17.0" like you said, I get an error with "1.3.6.1.2.1.43.10.2.1.4.1.1"

```
RequestFailedError: NoSuchName: 1.3.6.1.2.1.43.10.2.1.4.1.1
    at Req.Session.onSimpleGetResponse [as onResponse] (/home/martin/Trabajo/inkside/src/clients/inkside-electron/node_modules/net-snmp/index.js:2062:16)
    at Session.onMsg (/home/martin/Trabajo/inkside/src/clients/inkside-electron/node_modules/net-snmp/index.js:2036:9)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage [as onmessage] (dgram.js:861:8) {
  name: 'RequestFailedError',
  message: 'NoSuchName: 1.3.6.1.2.1.43.10.2.1.4.1.1',
  status: 2
}
```

**Comment by stephenwvickers** [comment]
@neumartin I missed this initially, but that makes sense, you are trying to get something that doesn't exist.

That OID is incomplete, and is part of a table so may not do what you expect.

**Comment by neumartin** [comment]
There is a way to execute several OID's but if one not exists I can get thw OID's that works?
Thanks!

**Comment by stephenwvickers** [comment]
In theory, use SNMP v2c.  If you are finding this is not the case I'd try a packet capture to see what's being returned from the device and see if it is returning errors correctly, per OID.

**Comment by neumartin** [comment]
I can't figure out the error, but using diferent OID's I get that I want:

1.3.6.1.2.1.43.5.1.1.16.1 = RICOH Aficio SP 3510DN (397b70) //model
1.3.6.1.2.1.43.10.2.1.4.1.1 = 147372 //prints counters
1.3.6.1.2.1.43.10.2.1.6.1.1 = 1 //number of colors
1.3.6.1.2.1.43.8.2.1.14.1.1 = RICOH //vendor name

Thanks for your support!!

**Comment by stephenwvickers** [comment]
@neumartin It would be useful to see a packet capture when it's failing to understand it a bit better.  I kind of feel incomplete not knowing what the actual problem was :)

**Comment by hluedeke** [comment]
Just a thought, but what is in the varbinds variable in your callback? Is it null, or are there still valid varbinds there? I haven't actually used this library in awhile, but it looks like you fail the whole callback on a returned error without checking the varbinds variable. Maybe you are still getting data and not realizing it? (You may have already thought of this-I thought I'd just state the obvious) 

```
// What is returning in varbinds?
session.get(oids, function (error, varbinds) {```
