### ISSUE TITLE
Incorrectly passing `req` object in call to `req.responseCb` when handling errors during response processing

### ISSUE THREAD

**Issue by ktsaou** [stephenwvickers/node-net-snmp#7]
Hi,

I noticed that when, within the callback function of `session.get()` there is a javascript error (e.g. an undefined variable), the module catches the error and calls again (!) the callback function, but this time its parameters are not `(error, varbinds)`, but `(varbinds, error)`.

I traced it in your code and found that it is called at the catch statement of `Session.prototype.onMsg()`. I added a console.log there, and yes, this is the place that it is being called.

There, you have a `req.responseCb (req, error);`, which is the inverse of what the callback function should accept.

Also, I am not sure if you should catch errors at the anonymous callback function.

**Comment by stephenwvickers** [comment]
I will take a look at this for you.

**Comment by ktsaou** [comment]
Thanks!
By the way, I have added your module to netdata:
demo here http://netdata.firehol.org/
docs here https://github.com/firehol/netdata/wiki/snmp.node.js

Excellent work! Thank you!

**Comment by stephenwvickers** [comment]
Fixed in 1.1.15 which will be published to npm shortly.
