### ISSUE TITLE
Underlying UDP ports are not closed when sessions go out of scope

### ISSUE THREAD

**Issue by sanket-mindstix** [stephenwvickers/node-net-snmp#9]
After request completion opened UDP port does not get closed, please investigate the issue. If we does not close the process UDP port remains open.

**Comment by stephenwvickers** [comment]
Please provide a test case.

**Comment by sanket-mindstix** [comment]
I am trying to fetch snmp data from my router in my application, my app is correctly fetching the data from router but after completion of fetching data snmp module is not closing the opened UDP port. I have check it with **lsof** utility. If you want I can share a sample code with you.

**Comment by stephenwvickers** [comment]
Yes, please provide an example program which emits the issue.

Also, please provide your node version and which version of net-snmp you are using.

**Comment by stephenwvickers** [comment]
Just so you now, when a new dgram is created it is unref'd:

```
	this.dgram = dgram.createSocket (this.transport);
	this.dgram.unref();
```

When a request is made the socket is ref'd again, then unref'd once the response has been processed.

This means it should not keep your program alive.

The only thing in net-snmp that would keep your program alive would be something like a timer used by for when it is waiting for responses - or a bug of course.

**Comment by sanket-mindstix** [comment]
node version - v4.0.0
net-snmp version - 1.1.13
Following is the code snippet, 
`
var netSnmp = require("net-snmp");

function getSNMPValues(ip, community, getCallback)
{
    try
    {
        var params =[];
        var mibList = getOidsArray();

        var oids = [];
        var session = netSnmp.createSession(ip, community);

        for(var i=0; i<mibList.length; i++)
        {
            var oid = mibList[i].oid;
            oids.push(oid);
        }

        session.get(oids, function(error, varbinds)
        {
            if(error)
            {
               return getCallback(error, null);
            }
            for (var i = 0; i < varbinds.length; i++)
            {
                if(netSnmp.isVarbindError (varbinds[i]))
                {
                    return getCallback("", null);
                }
                try
                {
                    var oidObject =
                    {
                        "oid":mibList[i].oid,
                        "value": varbinds[i].value.toString(),
                        "desc": mibList[i].mib,
                        "readOnly": mibList[i].readOnly
                    };
                    params.push(oidObject);
                }
                catch(error)
                {
                    console.error("Failure");
                    return getCallback(error, null);
                }
            }
            return getCallback(null, params);
        });
    }
    catch(error)
    {
        console.log(error.stack);
        return getCallback(error, null);
    }
}

function getOidsArray()
{
    var oids = [
        {
            "mib": "System Description for the entity",
            "oid": "1.3.6.1.2.1.1.1.0",
            "readOnly": true
        },
        {
            "mib" : "System uptime of that entity in milliseconds",
            "oid" : "1.3.6.1.2.1.1.3.0",
            "readOnly": true
        },
        {
            "mib" : "Contact email assigned to an entity",
            "oid" : "1.3.6.1.2.1.1.4.0",
            "readOnly": false
        },
        {
            "mib" : "System name assigned to an entity",
            "oid" : "1.3.6.1.2.1.1.5.0",
            "readOnly": false
        },
        {
            "mib" : "Location set for an entity",
            "oid" : "1.3.6.1.2.1.1.6.0",
            "readOnly": false
        }
    ];

    return oids;
}

var ipAddress = "192.168.2.1";
getSNMPValues(ipAddress,"public",function handleCallback(err,res){
    console.log(err);
    console.log(res);

});

console.log("IP quried " +ipAddress);
console.log("Process PID "+process.pid);

setInterval(function (){

},1000);`

To check opened port with lsof utility, please install it first at your machine using **sudo apt-get install lsof**.
After running above script, it will print PID, you use this pid with lsof utility to find opened UDP port,
following is the command to check open port,
**lsof -p PID**

**Comment by stephenwvickers** [comment]
This at the end of your snippet:

```
setInterval(function (){

},1000);
```

Will keep your code alive.

**Comment by sanket-mindstix** [comment]
I deliberately put that code to keep my snippet alive. My code remains alive is not my problem but the problem is UDP port gets opened even after I got successful or failure callback. 
In my app I am fetching data for many ip addresses continuously so at some point I am running out of UDP ports. That is my concern.

**Comment by stephenwvickers** [comment]
I think I can see the issue you are experience, let me take a closer look and I will get back to you.

**Comment by stephenwvickers** [comment]
Hi,

I believe the issue you are experiencing is down to not calling `session.close()` once you've finished with a session.

In your code the underlying UDP port will remain open until garbage collection occurs.

Either re-use the same session, or close the session once you have finished with it.

Steve

**Comment by sanket-mindstix** [comment]
Thanks, issue has been resolved after using session.close().

On Tue, Mar 1, 2016 at 12:05 AM, Stephen Vickers <notifications@github.com>
wrote:

> Hi,
>
> I believe the issue you are experiencing is down to not calling
> session.close() once you've finished with a session.
>
> In your code the underlying UDP port will remain open until garbage
> collection occurs.
>
> Either re-use the same session, or close the session once you have
> finished with it.
>
> Steve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephenwvickers/node-net-snmp/issues/9#issuecomment-190324105>
> .
>



-- 
Sanket Kulkarni.
Mindstix Software Labs
http://www.mindstix.com

Email: *sanket.kulkarni@mindstix.com <baljeet.singh@mindstix.com>*
Phone: +91 7276007159
Skype: sanket.kulkarni4

**Comment by hluedeke** [comment]
Do you mind including `session.close()` in your example code? I imagine it would be considered best practice, and it would help us noobs not inadvertently introduce leaks into our code :)

TIA!

**Comment by stephenwvickers** [comment]
@hluedeke Sure, I will add this to the next build.
